name: Testing Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking-out our Repo Code
        uses: actions/checkout@v4

      - name: Installing Node Js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Installing Node Modules
        run: npm ci

      - name: Running Test Scripts
        run: npm test
